name: Tarea Automatizada de ejecución de pruebas

env:
  PHP_VERSION: '8.x'
  SONAR_ORG: 'jorge-briceno'
  SONAR_PROJECT: 'jorge-briceno_proyectounidad3'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    name: CoverageReport
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Instalar dependencias
        run: composer install

      - name: Ejecutar pruebas con PHPUnit y generar cobertura
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit-Coverage-Report
          path: coverage.xml

      - name: Configurar SonarScanner
        run: |
          curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonarscanner.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH="$PATH:$(pwd)/sonar-scanner/bin"

      - name: Ejecutar SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT }} \
            -Dsonar.organization=${{ env.SONAR_ORG }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.php.tests.reportPath=coverage.xml

  bdd:
    name: BDDTests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Instalar dependencias
        run: composer install

      - name: Ejecutar pruebas con Behat y generar reporte HTML
        run: ./vendor/bin/behat --format=html --out=behat.html

      - name: Subir reporte HTML de Behat como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: Behat-HTML-Report
          path: behat.html

      - name: Desplegar reporte HTML de Behat en GitHub Pages
        if: github.ref == 'refs/heads/bddreporte'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: bddreporte
          publish_dir: .

      - name: Desplegar reporte HTML de Behat en otro entorno (ejemplo)
        if: github.ref == 'refs/heads/otroambiente'
        run: |
          # Comandos para desplegar en otro ambiente
          echo "Desplegando en otro ambiente"

