name: Tarea Automatizada de ejecución de pruebas

env:
  PHP_VERSION: '8.x'
  SONAR_ORG: 'jorge-briceno'
  SONAR_PROJECT: 'jorge-briceno_proyectounidad3'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    name: CoverageReport
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer install

      - name: Set permissions for PHPUnit
        run: chmod +x ./vendor/bin/phpunit

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml --testdox --test-suffix '.php' tests/Unit
        shell: bash

      - name: Upload PHPUnit coverage report
        uses: actions/upload-artifact@v4
        with:
          name: PHPUnit-Coverage-Report
          path: coverage.xml

      - name: Set up SonarScanner
        run: |
          curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonarscanner.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH="$PATH:$(pwd)/sonar-scanner/bin"

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT }} \
            -Dsonar.organization=${{ env.SONAR_ORG }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.php.tests.reportPath=coverage.xml

  bdd:
    name: BDDTests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer install

      - name: Set permissions for Behat
        run: chmod +x ./vendor/bin/behat

      - name: Run Behat tests and generate HTML report
        run: ./vendor/bin/behat --format=html --out=behat.html

      - name: Upload Behat HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Behat-HTML-Report
          path: behat.html

      - name: Deploy Behat HTML report
        if: github.ref == 'refs/heads/bddreporte'  # Ejecutar solo si se está en la rama 'bddreporte'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: bddreporte
          publish_dir: .
          force_orphan: true
          keep_files: false
          cname: behat-report
